name: Deploy Flask App to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecrgit push origin main
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push Docker image
      run: |
        docker build -t flask-app ./app
        docker tag flask-app:latest ${{ steps.login-ecr.outputs.registry }}/flask-app:latest
        docker push ${{ steps.login-ecr.outputs.registry }}/flask-app:latest

    - name: Update EKS deployment
      run: |
        aws eks update-kubeconfig --region ap-south-1 --name demo-cluster
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
